#!/usr/bin/env bash
# update-helius-rpc.sh — Update Helius RPC URL in all .env files and restart services
#
# Usage:
#   HELIUS_API_KEY="your-new-key" bash /mnt/data/mythic-l2/infra/update-helius-rpc.sh
#
# Run ON Server 1 (20.96.180.64).
set -euo pipefail

if [ -z "${HELIUS_API_KEY:-}" ]; then
    echo "ERROR: HELIUS_API_KEY environment variable is required."
    echo ""
    echo "Usage:"
    echo "  HELIUS_API_KEY='your-api-key-here' bash $0"
    echo ""
    echo "Get your API key from: https://dashboard.helius.dev/"
    exit 1
fi

HELIUS_RPC_URL="https://mainnet.helius-rpc.com/?api-key=${HELIUS_API_KEY}"
BASE="/mnt/data"

echo "=== Update Helius RPC URL ==="
echo "New RPC URL: https://mainnet.helius-rpc.com/?api-key=****${HELIUS_API_KEY: -4}"
echo ""

# ── .env files to update ──────────────────────────────────────────────────

ENV_FILES=(
    "${BASE}/mythic-l2/website/.env.local"
    "${BASE}/mythic-l2/relayer/.env"
    "${BASE}/mythic-l2/services/settlement/.env"
    "${BASE}/mythic-l2/services/supply-oracle/.env"
    "${BASE}/mythic-money/.env"
    "${BASE}/mythic-swap/.env"
    "${BASE}/mythic-l2/services/reward-distributor/.env"
)

UPDATED=0
CREATED=0
SKIPPED=0

for env_file in "${ENV_FILES[@]}"; do
    dir=$(dirname "${env_file}")
    if [ ! -d "${dir}" ]; then
        echo "  [SKIP] ${env_file} (directory not found)"
        SKIPPED=$((SKIPPED + 1))
        continue
    fi

    if [ -f "${env_file}" ]; then
        # Check if HELIUS_RPC_URL or L1_RPC_URL already exists
        if grep -q "^HELIUS_RPC_URL=" "${env_file}" 2>/dev/null; then
            sed -i "s|^HELIUS_RPC_URL=.*|HELIUS_RPC_URL=${HELIUS_RPC_URL}|" "${env_file}"
            echo "  [UPDATED] ${env_file} (HELIUS_RPC_URL)"
            UPDATED=$((UPDATED + 1))
        elif grep -q "^L1_RPC_URL=" "${env_file}" 2>/dev/null; then
            sed -i "s|^L1_RPC_URL=.*|L1_RPC_URL=${HELIUS_RPC_URL}|" "${env_file}"
            echo "  [UPDATED] ${env_file} (L1_RPC_URL)"
            UPDATED=$((UPDATED + 1))
        elif grep -q "^NEXT_PUBLIC_L1_RPC=" "${env_file}" 2>/dev/null; then
            sed -i "s|^NEXT_PUBLIC_L1_RPC=.*|NEXT_PUBLIC_L1_RPC=${HELIUS_RPC_URL}|" "${env_file}"
            echo "  [UPDATED] ${env_file} (NEXT_PUBLIC_L1_RPC)"
            UPDATED=$((UPDATED + 1))
        else
            # Append the key
            echo "" >> "${env_file}"
            echo "# Helius RPC (Solana L1 mainnet)" >> "${env_file}"
            echo "HELIUS_RPC_URL=${HELIUS_RPC_URL}" >> "${env_file}"
            echo "  [APPENDED] ${env_file}"
            UPDATED=$((UPDATED + 1))
        fi
    else
        # Create new .env file
        cat > "${env_file}" << EOF
# Mythic L2 Environment Configuration
# Generated by update-helius-rpc.sh on $(date -u '+%Y-%m-%d %H:%M:%S UTC')

# Solana L1 Mainnet RPC (Helius)
HELIUS_RPC_URL=${HELIUS_RPC_URL}
L1_RPC_URL=${HELIUS_RPC_URL}
EOF
        echo "  [CREATED] ${env_file}"
        CREATED=$((CREATED + 1))
    fi
done

echo ""
echo "Updated: ${UPDATED}, Created: ${CREATED}, Skipped: ${SKIPPED}"
echo ""

# ── Restart affected PM2 services ─────────────────────────────────────────

echo "Restarting affected PM2 services..."

PM2_SERVICES=(
    "mythic-website"
    "mythic-relayer"
    "mythic-settlement"
    "mythic-supply-oracle"
    "mythic-money-website"
    "mythic-swap-website"
    "mythic-reward-distributor"
)

for svc in "${PM2_SERVICES[@]}"; do
    if pm2 describe "${svc}" &>/dev/null; then
        pm2 restart "${svc}" --update-env 2>/dev/null
        echo "  [RESTARTED] ${svc}"
    else
        echo "  [SKIP] ${svc} (not running in PM2)"
    fi
done

echo ""
echo "=== Helius RPC update complete ==="
echo ""
echo "Verify:"
echo "  curl -s https://mythic.sh/api/l1-rpc | head -c 200"
echo "  pm2 status"
